### ISSUE TITLE
Export Duration type externally

### ISSUE THREAD

**Issue by JoltCode** [upstash/ratelimit-js#118]
Export the `Duration` type https://github.com/upstash/ratelimit-js/blob/492fe7e864b8cff08857c1115d8fa4cfd7b2934e/src/duration.ts#L2 to the external exports, so it can be used when using the library, so you don't have to do `Parameters<typeof Ratelimit.slidingWindow>[1]` to access the type.

**Comment by ogzhanolguncu** [comment]
Thanks for pointing that out. We'll fix this ASAP.

**Comment by JoltCode** [comment]
Thanks so much 😄
