### ISSUE TITLE
blockUntilReady and cf workers

### ISSUE THREAD

**Issue by bkniffler** [upstash/ratelimit-js#70]
blockUntilReady relies on Date.now, but in cf worker env, Date.now does not reliably progress as in nodeJS or browser env. 

https://developers.cloudflare.com/workers/runtime-apis/web-standards/

Maybe this could get added to docs, it might safe a few people from headaches.
<img width="721" alt="Bildschirmfoto 2023-11-20 um 15 23 04" src="https://github.com/upstash/ratelimit/assets/4349324/1b66f7cc-f4cd-4ed5-9b18-0f4c8ec0dceb">

**Comment by ogzhanolguncu** [comment]
bump

**Comment by bkniffler** [comment]
Is this going to be addressed eventually? This is a serious concern that most users will probably not be aware of.

**Comment by ogzhanolguncu** [comment]
We’ll see what we can do and if we can’t find a good solution, we’ll document in our docs. Sorry for late reply.

**Comment by ogzhanolguncu** [comment]
Issue is finally addressed here in the docs: https://github.com/upstash/docs/pull/121
